import StyledComponentsRegistry from "@lib/registry";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header/Header";
import { ContentLayout } from "@lib/contentLayout";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Game BD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Header />
          <ContentLayout>
            {children}
            <div id="modal" />
          </ContentLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
